### ISSUE TITLE
Header Issue

### ISSUE THREAD

**Issue by Amin0096** [PDFTron/pdftron-cordova#2]
1. Header issue is there.I attached link [ https://we.tl/t-W6uHaFA6DF)] . Please download and see header is going up. if you open second time pdftron header is going up. How to fix it. 
2. How to save pdf file in local storage .
3. How to do default landscape view.
4. PPT file is not opening in pdftron. How to open ppt file?.
5. How to open pdf file into 16:9 ratio. 
6. In each and every page is written PDFTRON in background. How to remove that one.

**Comment by sgong-pdftron** [comment]
@Amin0096 

3. Have you tried using cordova orientation, for example:
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-screen-orientation/

4. PPT support is coming up in next major release

5. Can you please clarify what this means?

6. You are using a demo license key, you will need to obtain a commercial license key to remove the demo stamps, see https://www.pdftron.com/licensing

**Comment by sgong-pdftron** [comment]
@Amin0096 

1. This is fixed in https://github.com/PDFTron/pdftron-cordova/commit/41769c0a481931f576d766f1b3de4674ea4ac7c4, can you please try it out? Thanks!

**Comment by Amin0096** [comment]
Hello,

Thanks for cleared header issue. And I checked cordova orientation. it is locked the orientation. I don't want like that.I am using pdftron in my application. if i close the pdftron the whole application' orientation is locked.  
5. I pdf file should be open into aspect ratio 16:9;
2.How to save pdf file in local storage .

Kind Regards
Amin

**Comment by sgong-pdftron** [comment]
@Amin0096 

Orientation and aspect ratio is very unique to your application.
My suggestion would be forking this repository and modify the PDFTron source to achieve these requirements.

2. We will add props for you to pass in cache location soon. If you need this urgently, you can remove the following line: https://github.com/PDFTron/pdftron-cordova/blob/41769c0a481931f576d766f1b3de4674ea4ac7c4/src/android/com/pdftron/cordova/PDFTron.java#L80, this should save the downloaded file to the Downloads folder

**Comment by Amin0096** [comment]
Hello,

I checked that you mentioned here about storing pdf file in download folder. But still it is not storing in any folder. Can give me proper solutions. How to store data in download folder.

Kind Regards

**Comment by sgong-pdftron** [comment]
@Amin0096 

Android runtime permission (https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#runtime-permissions-cordova-android-500) is required to access the Downloads folder. May I ask if you are requesting storage permission at runtime?

**Comment by Amin0096** [comment]
Where I need to add run time permission.

**Comment by sgong-pdftron** [comment]
@Amin0096 

You can either find another cordova plugin that has such functionality or add it to your android project directly (as described in the official cordova article). Could you give that a try?

**Comment by Amin0096** [comment]
How to save pdf file in local storage (like in download folder).

**Comment by sgong-pdftron** [comment]
@Amin0096  you can specify any path as you wish with "openUrlCachePath" API. Does that work for you?

**Comment by Amin0096** [comment]
I added this code. 
.useSupportActionBar(false)
                .fullscreenModeEnabled(false)
                .multiTabEnabled(false)
                .saveCopyExportPath(cordova.getContext().getExternalCacheDir().getAbsolutePath())
                .download(cordova.getContext().getExternalCacheDir().getAbsolutePath());


but i am getting error

 error: cannot find symbol
                .openUrlDownload(cordova.getContext().getExternalCacheDir().getAbsolutePath());
                ^
  symbol:   method openUrlDownload(String)
  location: class Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

**Comment by Amin0096** [comment]
I added this code.
.useSupportActionBar(false)
.fullscreenModeEnabled(false)
.multiTabEnabled(false)
.saveCopyExportPath(cordova.getContext().getExternalCacheDir().getAbsolutePath())
.download(cordova.getContext().getExternalCacheDir().getAbsolutePath());

but i am getting error

error: cannot find symbol
.download(cordova.getContext().getExternalCacheDir().getAbsolutePath());
^
symbol: method openUrlDownload(String)
location: class Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

**Comment by sgong-pdftron** [comment]
@Amin0096 

openUrlCachePath(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath())

**Comment by Amin0096** [comment]
We are getting 
error: cannot find symbol             .openUrlCachePath(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath());
                                  ^
  symbol:   variable Environment
  location: class PDFTron
> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by sgong-pdftron** [comment]
@Amin0096 

Can you add import:

`import android.os.Environment;`

If you are using Android Studio, you can auto import with alt+ enter key. Thanks.

**Comment by Amin0096** [comment]
Yes I imported
import android.os.Environment;. Now build is working. but pdf file is not downloading in pdftron.Getting downloading failed

**Comment by sgong-pdftron** [comment]
@Amin0096 have you finished requesting for runtime permission? (https://developer.android.com/training/permissions/requesting) One thing you can try is go to System Settings -> Apps -> find your app -> Permissions -> turn on storage permission. Then it should have access to Downloads folder.

**Comment by Amin0096** [comment]
Now it is working. Great!.
But I have query regarding permission and pdftron.
1. How to give the permission to ask user to enable the storage permission in your mobile.
2. How to open ppt file in pdftron. And we can save ppt into pdf format (pdf file).

**Comment by sgong-pdftron** [comment]
@Amin0096 

> Permission:

There is a utility method you can use to request permission in "onResume" method of your main activity:

import com.pdftron.pdf.utils.Utils;
Utils.requestStoragePermissions(this, null, RequestCode.STORAGE_1);

> PPT

This is on our road map. If this is a blocking issue for you, please contact support at support@pdftron.com. Thanks.

**Comment by sgong-pdftron** [comment]
@Amin0096 I am closing this issue as it seems to be working for you now. Please contact us at support@pdftron.com if you have any issues in the future. Thanks.
